export type SkillName =
    | "Admin"
    | "Air/Raft"
    | "Auto Pistol"
    | "Auto Rifle"
    | "Blade"
    | "Blade Cbt"
    | "Bayonet"
    | "Body Pistol"
    | "Broadsword"
    | "Bribery"
    | "Brawling"
    | "Carbine"
    | "Computer"
    | "Cudgel"
    | "Cutlass"
    | "Dagger"
    | "Electronics"
    | "Engineering"
    | "Fwd Obsvr"
    | "Forgery"
    | "Foil"
    | "Gambling"
    | "Grav Belt"
    | "Ground Car"
    | "Gun Cbt"
    | "Gunnery"
    | "Halberd"
    | "Hovercraft"
    | "Jack-o-T"
    | "Laser Carbine"
    | "Laser Rifle"
    | "Leader"
    | "Mechanical"
    | "Medical"
    | "Navigation"
    | "Pilot"
    | "Pike"
    | "Revolver"
    | "Rifle"
    | "SMG"
    | "Shotgun"
    | "Spear"
    | "Steward"
    | "Streetwise"
    | "Sword"
    | "Tactics"
    | "Vacc Suit"
    | "Vehicle"
    | "Watercraft"
    | "Winged Craft"
    | "Ship's Boat";

export type ItemName =
    | "High Psg"
    | "Low Psg"
    | "Mid Psg"
    | "Travellers'"
    | SkillName;

export type WeaponCategory = "blade" | "pistol" | "weapon" | "gun";

export type D6Table<T> = readonly [T, T, T, T, T, T];

export type D7Table<T> = readonly [T, T, T, T, T, T, T];
